import type { Config } from 'tailwindcss'

const config: Config = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#f0fdfe',
                    100: '#ccfbfe',
                    200: '#99f6fd',
                    300: '#5ee0e5',
                    400: '#22d3ee',
                    500: '#06b6d4',
                    600: '#0891b2',
                    700: '#0e7490',
                    800: '#155e75',
                    900: '#164e63',
                },
                accent: {
                    50: '#f0f9ff',
                    100: '#e0f2fe',
                    200: '#bae6fd',
                    300: '#7dd3fc',
                    400: '#38bdf8',
                    500: '#0ea5e9',
                    600: '#0284c7',
                    700: '#0369a1',
                    800: '#075985',
                    900: '#0c4a6e',
                },
                electric: {
                    50: '#faf5ff',
                    100: '#f3e8ff',
                    200: '#e9d5ff',
                    300: '#d8b4fe',
                    400: '#c084fc',
                    500: '#a855f7',
                    600: '#9333ea',
                    700: '#7c3aed',
                    800: '#6b21a8',
                    900: '#581c87',
                },
                dark: {
                    50: '#f8fafc',
                    100: '#f1f5f9',
                    200: '#e2e8f0',
                    300: '#cbd5e1',
                    400: '#94a3b8',
                    500: '#64748b',
                    600: '#475569',
                    700: '#334155',
                    800: '#1e293b',
                    900: '#0f172a',
                    950: '#020617',
                },
            },
            fontFamily: {
                sans: ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
                ai: ['Orbitron', 'Space Grotesk', 'sans-serif'],
                logo: ['Space Grotesk', 'Orbitron', 'sans-serif'],
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
                'ai-circuit': 'linear-gradient(45deg, transparent 30%, rgba(94, 224, 229, 0.1) 50%, transparent 70%)',
                'neural-net': 'radial-gradient(circle at 20% 50%, rgba(94, 224, 229, 0.1) 0%, transparent 40%), radial-gradient(circle at 80% 50%, rgba(168, 85, 247, 0.1) 0%, transparent 40%)',
                'data-flow': 'linear-gradient(90deg, transparent, rgba(94, 224, 229, 0.6), transparent)',
                'particle-field': 'radial-gradient(circle at 25% 25%, rgba(94, 224, 229, 0.03) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(168, 85, 247, 0.03) 0%, transparent 50%), radial-gradient(circle at 50% 10%, rgba(14, 165, 233, 0.03) 0%, transparent 50%)',
            },
            animation: {
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'bounce-slow': 'bounce 3s infinite',
                'float': 'float 6s ease-in-out infinite',
                'float-delayed': 'float 6s ease-in-out infinite 2s',
                'float-slow': 'float 8s ease-in-out infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
                'glow-intense': 'glow-intense 1.5s ease-in-out infinite alternate',
                'circuit': 'circuit 8s linear infinite',
                'data-flow': 'data-flow 3s ease-in-out infinite',
                'particle-drift': 'particle-drift 20s linear infinite',
                'neural-pulse': 'neural-pulse 4s ease-in-out infinite',
                'morph': 'morph 6s ease-in-out infinite',
                'spin-slow': 'spin 8s linear infinite',
                'spin-reverse': 'spin-reverse 10s linear infinite',
                'fade-in-up': 'fade-in-up 0.6s ease-out',
                'scale-in': 'scale-in 0.4s ease-out',
                'slide-in-right': 'slide-in-right 0.5s ease-out',
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
                glow: {
                    '0%': { boxShadow: '0 0 20px rgba(94, 224, 229, 0.3)' },
                    '100%': { boxShadow: '0 0 40px rgba(94, 224, 229, 0.6)' },
                },
                'glow-intense': {
                    '0%': { boxShadow: '0 0 30px rgba(94, 224, 229, 0.4), 0 0 60px rgba(94, 224, 229, 0.2)' },
                    '100%': { boxShadow: '0 0 50px rgba(94, 224, 229, 0.8), 0 0 80px rgba(94, 224, 229, 0.4)' },
                },
                circuit: {
                    '0%': { backgroundPosition: '0% 0%' },
                    '100%': { backgroundPosition: '100% 100%' },
                },
                'data-flow': {
                    '0%': { transform: 'translateX(-100%)', opacity: '0' },
                    '50%': { opacity: '1' },
                    '100%': { transform: 'translateX(100%)', opacity: '0' },
                },
                'particle-drift': {
                    '0%': { transform: 'translateY(0px) translateX(0px) rotate(0deg)' },
                    '33%': { transform: 'translateY(-30px) translateX(20px) rotate(120deg)' },
                    '66%': { transform: 'translateY(-10px) translateX(-15px) rotate(240deg)' },
                    '100%': { transform: 'translateY(0px) translateX(0px) rotate(360deg)' },
                },
                'neural-pulse': {
                    '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
                    '50%': { opacity: '0.8', transform: 'scale(1.05)' },
                },
                morph: {
                    '0%, 100%': { borderRadius: '30% 70% 70% 30% / 30% 30% 70% 70%' },
                    '25%': { borderRadius: '70% 30% 50% 50% / 60% 60% 40% 40%' },
                    '50%': { borderRadius: '50% 50% 30% 70% / 40% 60% 60% 40%' },
                    '75%': { borderRadius: '30% 70% 70% 30% / 70% 40% 60% 30%' },
                },
                'spin-reverse': {
                    '0%': { transform: 'rotate(360deg)' },
                    '100%': { transform: 'rotate(0deg)' },
                },
                'fade-in-up': {
                    '0%': { opacity: '0', transform: 'translateY(30px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'scale-in': {
                    '0%': { opacity: '0', transform: 'scale(0.8)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                'slide-in-right': {
                    '0%': { opacity: '0', transform: 'translateX(50px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
            },
            backdropBlur: {
                'xs': '2px',
            },
            transitionDuration: {
                '2000': '2000ms',
                '3000': '3000ms',
            },
        },
    },
    plugins: [],
}
export default config 